CREATE TABLE "opposition" (
                     `opposition`	TEXT NOT NULL
                  );
INSERT INTO `opposition` VALUES ('Ghoul.');
INSERT INTO `opposition` VALUES ('Goblin.');
INSERT INTO `opposition` VALUES ('Hydra.');
INSERT INTO `opposition` VALUES ('Golem.');
INSERT INTO `opposition` VALUES ('Blood thorn.');
INSERT INTO `opposition` VALUES ('Worg.');
INSERT INTO `opposition` VALUES ('Ettin.');
INSERT INTO `opposition` VALUES ('Worg rider.');
INSERT INTO `opposition` VALUES ('Succubus.');
INSERT INTO `opposition` VALUES ('Cockatrice.');
INSERT INTO `opposition` VALUES ('Werepanther.');
INSERT INTO `opposition` VALUES ('Hired thugs.');
INSERT INTO `opposition` VALUES ('Minotaur.');
INSERT INTO `opposition` VALUES ('Cultists.');
INSERT INTO `opposition` VALUES ('Evil cleric.');
INSERT INTO `opposition` VALUES ('Bear.');
INSERT INTO `opposition` VALUES ('Doppelganger.');
INSERT INTO `opposition` VALUES ('Orc.');
INSERT INTO `opposition` VALUES ('Wraith.');
INSERT INTO `opposition` VALUES ('Misguided hero.');
INSERT INTO `opposition` VALUES ('Kobolds.');
INSERT INTO `opposition` VALUES ('Demon.');
INSERT INTO `opposition` VALUES ('Gnoll.');
INSERT INTO `opposition` VALUES ('Assassin.');
INSERT INTO `opposition` VALUES ('Chimera.');
INSERT INTO `opposition` VALUES ('Angry mob.');
INSERT INTO `opposition` VALUES ('Bandit.');
INSERT INTO `opposition` VALUES ('Saboteur.');
INSERT INTO `opposition` VALUES ('Troll.');
INSERT INTO `opposition` VALUES ('Necromancer.');
INSERT INTO `opposition` VALUES ('Lunatic.');
INSERT INTO `opposition` VALUES ('Rabid animal.');
INSERT INTO `opposition` VALUES ('Bounty hunter.');
INSERT INTO `opposition` VALUES ('Dragon.');
INSERT INTO `opposition` VALUES ('Ogre.');
INSERT INTO `opposition` VALUES ('Zombie.');
INSERT INTO `opposition` VALUES ('Dark elf.');
INSERT INTO `opposition` VALUES ('Imp.');
INSERT INTO `opposition` VALUES ('Abomination.');
INSERT INTO `opposition` VALUES ('Wolf.');
INSERT INTO `opposition` VALUES ('Skeleton.');
INSERT INTO `opposition` VALUES ('Shadow.');
INSERT INTO `opposition` VALUES ('Ravager.');
INSERT INTO `opposition` VALUES ('Giant.');
INSERT INTO `opposition` VALUES ('Vampire.');
INSERT INTO `opposition` VALUES ('Spy.');
INSERT INTO `opposition` VALUES ('Giant vermin.');
INSERT INTO `opposition` VALUES ('Mindless horde.');
INSERT INTO `opposition` VALUES ('Carnivorous plant.');
INSERT INTO `opposition` VALUES ('Ghost.');
INSERT INTO `opposition` VALUES ('Enemy soldier.');
INSERT INTO `opposition` VALUES ('Marauder.');
INSERT INTO `opposition` VALUES ('Goblin hoard.');
INSERT INTO `opposition` VALUES ('Behemoth.');
INSERT INTO `opposition` VALUES ('Dire animal.');
INSERT INTO `opposition` VALUES ('Death knight.');
INSERT INTO `opposition` VALUES ('Common criminal.');
INSERT INTO `opposition` VALUES ('Wood nymph.');
INSERT INTO `opposition` VALUES ('Thug.');
INSERT INTO `opposition` VALUES ('Wight.');
INSERT INTO `opposition` VALUES ('Slaver.');
INSERT INTO `opposition` VALUES ('Gorgon.');
INSERT INTO `opposition` VALUES ('Slime.');
INSERT INTO `opposition` VALUES ('Troglodyte.');
INSERT INTO `opposition` VALUES ('Warlock.');
INSERT INTO `opposition` VALUES ('Invaders.');
INSERT INTO `opposition` VALUES ('Illusion.');
INSERT INTO `opposition` VALUES ('Gargantuan.');
INSERT INTO `opposition` VALUES ('Gargoyle.');
INSERT INTO `opposition` VALUES ('Harpy.');
INSERT INTO `opposition` VALUES ('Thief.');
INSERT INTO `opposition` VALUES ('Centaur.');
INSERT INTO `opposition` VALUES ('Hobgoblin.');
INSERT INTO `opposition` VALUES ('Basilisk.');
INSERT INTO `opposition` VALUES ('Cyclops.');
INSERT INTO `opposition` VALUES ('Naga.');
INSERT INTO `opposition` VALUES ('Soul-stealer.');
INSERT INTO `opposition` VALUES ('Mercenaries.');
INSERT INTO `opposition` VALUES ('Nightmare.');
INSERT INTO `opposition` VALUES ('Pack of feral dogs.');
INSERT INTO `opposition` VALUES ('Lizard man.');
INSERT INTO `opposition` VALUES ('Werewolf.');
INSERT INTO `opposition` VALUES ('Guards.');
INSERT INTO `opposition` VALUES ('Mage.');
INSERT INTO `opposition` VALUES ('Traitor.');
INSERT INTO `opposition` VALUES ('Swarm.');
INSERT INTO `opposition` VALUES ('Will-o-wisp.');
INSERT INTO `opposition` VALUES ('Beholder.');
INSERT INTO `opposition` VALUES ('Elemental.');
INSERT INTO `opposition` VALUES ('Giant snake.');
INSERT INTO `opposition` VALUES ('Giant spider.');
INSERT INTO `opposition` VALUES ('Agent of the crown.');
INSERT INTO `opposition` VALUES ('Manticore.');
INSERT INTO `opposition` VALUES ('Force of nature.');
INSERT INTO `opposition` VALUES ('Tiger.');
INSERT INTO `opposition` VALUES ('Plague-carrying rodents.');
INSERT INTO `opposition` VALUES ('Sorcerer.');
INSERT INTO `opposition` VALUES ('Witch.');
INSERT INTO `opposition` VALUES ('Brigand.');
INSERT INTO `opposition` VALUES ('Lion.');



