CREATE TABLE "skill" (
                     `skill`	TEXT NOT NULL
                  );
INSERT INTO `skill` VALUES ('Rope use.');
INSERT INTO `skill` VALUES ('Drinking.');
INSERT INTO `skill` VALUES ('Ancient lore.');
INSERT INTO `skill` VALUES ('Blind-fighting.');
INSERT INTO `skill` VALUES ('History.');
INSERT INTO `skill` VALUES ('Languages.');
INSERT INTO `skill` VALUES ('Boating.');
INSERT INTO `skill` VALUES ('Poetry.');
INSERT INTO `skill` VALUES ('Philosophy.');
INSERT INTO `skill` VALUES ('Divination.');
INSERT INTO `skill` VALUES ('Shield use.');
INSERT INTO `skill` VALUES ('Listening.');
INSERT INTO `skill` VALUES ('Wrestling.');
INSERT INTO `skill` VALUES ('Marksmanship.');
INSERT INTO `skill` VALUES ('Night vision.');
INSERT INTO `skill` VALUES ('Artistic ability.');
INSERT INTO `skill` VALUES ('Jumping.');
INSERT INTO `skill` VALUES ('Gem cutting.');
INSERT INTO `skill` VALUES ('Mining.');
INSERT INTO `skill` VALUES ('Running.');
INSERT INTO `skill` VALUES ('Curses.');
INSERT INTO `skill` VALUES ('Escape artist.');
INSERT INTO `skill` VALUES ('Reading lips.');
INSERT INTO `skill` VALUES ('Awareness.');
INSERT INTO `skill` VALUES ('Lock picking.');
INSERT INTO `skill` VALUES ('Appraising.');
INSERT INTO `skill` VALUES ('Dodge.');
INSERT INTO `skill` VALUES ('Gambling.');
INSERT INTO `skill` VALUES ('Healing.');
INSERT INTO `skill` VALUES ('Intimidation.');
INSERT INTO `skill` VALUES ('Ventriloquism.');
INSERT INTO `skill` VALUES ('Masonry.');
INSERT INTO `skill` VALUES ('Pickpocketing.');
INSERT INTO `skill` VALUES ('Agriculture.');
INSERT INTO `skill` VALUES ('Cobbling.');
INSERT INTO `skill` VALUES ('Hunting.');
INSERT INTO `skill` VALUES ('Tracking.');
INSERT INTO `skill` VALUES ('Seamstress/tailor.');
INSERT INTO `skill` VALUES ('Farming.');
INSERT INTO `skill` VALUES ('Literacy.');
INSERT INTO `skill` VALUES ('Necromancy.');
INSERT INTO `skill` VALUES ('Arcane lore.');
INSERT INTO `skill` VALUES ('Forgery.');
INSERT INTO `skill` VALUES ('Sleight of hand.');
INSERT INTO `skill` VALUES ('Endurance.');
INSERT INTO `skill` VALUES ('Seamanship.');
INSERT INTO `skill` VALUES ('Medicine.');
INSERT INTO `skill` VALUES ('Climbing.');
INSERT INTO `skill` VALUES ('Armorer.');
INSERT INTO `skill` VALUES ('Bowyer/fletcher.');
INSERT INTO `skill` VALUES ('Riding.');
INSERT INTO `skill` VALUES ('Cartography.');
INSERT INTO `skill` VALUES ('Negotiation.');
INSERT INTO `skill` VALUES ('Balance.');
INSERT INTO `skill` VALUES ('Leadership.');
INSERT INTO `skill` VALUES ('Law.');
INSERT INTO `skill` VALUES ('Disguise.');
INSERT INTO `skill` VALUES ('Brewing.');
INSERT INTO `skill` VALUES ('Navigation.');
INSERT INTO `skill` VALUES ('Throwing.');
INSERT INTO `skill` VALUES ('Unarmed combat.');
INSERT INTO `skill` VALUES ('Athletic.');
INSERT INTO `skill` VALUES ('Herbalism.');
INSERT INTO `skill` VALUES ('Etiquette.');
INSERT INTO `skill` VALUES ('Astrology.');
INSERT INTO `skill` VALUES ('Streetwise.');
INSERT INTO `skill` VALUES ('Undead lore.');
INSERT INTO `skill` VALUES ('Foraging.');
INSERT INTO `skill` VALUES ('Spell craft.');
INSERT INTO `skill` VALUES ('Runes.');
INSERT INTO `skill` VALUES ('Cooking.');
INSERT INTO `skill` VALUES ('Stealth.');
INSERT INTO `skill` VALUES ('Siege works.');
INSERT INTO `skill` VALUES ('Tactics.');
INSERT INTO `skill` VALUES ('Scribe.');
INSERT INTO `skill` VALUES ('Poisons.');
INSERT INTO `skill` VALUES ('Nature lore.');
INSERT INTO `skill` VALUES ('Wilderness survival.');
INSERT INTO `skill` VALUES ('Seduction.');
INSERT INTO `skill` VALUES ('Archery.');
INSERT INTO `skill` VALUES ('Concentration.');
INSERT INTO `skill` VALUES ('Engineering.');
INSERT INTO `skill` VALUES ('Weaponsmithing.');
INSERT INTO `skill` VALUES ('Alchemy.');
INSERT INTO `skill` VALUES ('Blacksmithing.');
INSERT INTO `skill` VALUES ('Smelting.');
INSERT INTO `skill` VALUES ('Sword fighting.');
INSERT INTO `skill` VALUES ('Direction sense.');
INSERT INTO `skill` VALUES ('First aid.');
INSERT INTO `skill` VALUES ('Detect/disarm traps.');
INSERT INTO `skill` VALUES ('Pottery.');
INSERT INTO `skill` VALUES ('Prophecy.');
INSERT INTO `skill` VALUES ('Bluffing.');
INSERT INTO `skill` VALUES ('Weapon improvisation.');
INSERT INTO `skill` VALUES ('Storytelling.');
INSERT INTO `skill` VALUES ('Animal handling.');
INSERT INTO `skill` VALUES ('Performing arts.');
INSERT INTO `skill` VALUES ('Mountaineering.');
INSERT INTO `skill` VALUES ('Two-weapon fighting.');
INSERT INTO `skill` VALUES ('Danger sense.');
INSERT INTO `skill` VALUES ('Surgery.');
INSERT INTO `skill` VALUES ('Fire-building.');
INSERT INTO `skill` VALUES ('Weather sense.');
INSERT INTO `skill` VALUES ('Local history.');
INSERT INTO `skill` VALUES ('Jousting.');
INSERT INTO `skill` VALUES ('Information gathering.');
INSERT INTO `skill` VALUES ('Leatherworking.');
INSERT INTO `skill` VALUES ('Bartering.');
INSERT INTO `skill` VALUES ('Taunting.');
INSERT INTO `skill` VALUES ('Animal lore.');
INSERT INTO `skill` VALUES ('Dungeoneering.');
INSERT INTO `skill` VALUES ('Alertness.');
INSERT INTO `skill` VALUES ('Planar lore.');
INSERT INTO `skill` VALUES ('Swimming.');
INSERT INTO `skill` VALUES ('Anatomy.');
INSERT INTO `skill` VALUES ('Persuasion.');
INSERT INTO `skill` VALUES ('Carpentry.');
INSERT INTO `skill` VALUES ('Planar survival.');
INSERT INTO `skill` VALUES ('Diplomacy.');
INSERT INTO `skill` VALUES ('Politics.');
INSERT INTO `skill` VALUES ('Sense motives.');
INSERT INTO `skill` VALUES ('Rituals.');
INSERT INTO `skill` VALUES ('Fishing.');
INSERT INTO `skill` VALUES ('Theology.');
INSERT INTO `skill` VALUES ('Begging.');
INSERT INTO `skill` VALUES ('Weapon specialization.');
INSERT INTO `skill` VALUES ('Infiltration.');
INSERT INTO `skill` VALUES ('Search/detect hidden.');
INSERT INTO `skill` VALUES ('Bureaucracy.');



