CREATE TABLE "subject" (
                     `subject`	TEXT NOT NULL
                  );
INSERT INTO `subject` VALUES ('Peace.');
INSERT INTO `subject` VALUES ('New ideas.');
INSERT INTO `subject` VALUES ('Wounds.');
INSERT INTO `subject` VALUES ('Intrigues.');
INSERT INTO `subject` VALUES ('Misfortune.');
INSERT INTO `subject` VALUES ('Dispute.');
INSERT INTO `subject` VALUES ('Animals.');
INSERT INTO `subject` VALUES ('Food.');
INSERT INTO `subject` VALUES ('Attention.');
INSERT INTO `subject` VALUES ('Bureaucracy.');
INSERT INTO `subject` VALUES ('Fame.');
INSERT INTO `subject` VALUES ('Success.');
INSERT INTO `subject` VALUES ('Extravagance.');
INSERT INTO `subject` VALUES ('Anger.');
INSERT INTO `subject` VALUES ('Friendship.');
INSERT INTO `subject` VALUES ('Tension.');
INSERT INTO `subject` VALUES ('Danger.');
INSERT INTO `subject` VALUES ('War.');
INSERT INTO `subject` VALUES ('Pain.');
INSERT INTO `subject` VALUES ('A project.');
INSERT INTO `subject` VALUES ('Disruption.');
INSERT INTO `subject` VALUES ('Expectations.');
INSERT INTO `subject` VALUES ('The mundane.');
INSERT INTO `subject` VALUES ('Wishes.');
INSERT INTO `subject` VALUES ('Environment.');
INSERT INTO `subject` VALUES ('Fears.');
INSERT INTO `subject` VALUES ('The spiritual.');
INSERT INTO `subject` VALUES ('Opulance.');
INSERT INTO `subject` VALUES ('Benefits.');
INSERT INTO `subject` VALUES ('Balance.');
INSERT INTO `subject` VALUES ('Legal matters.');
INSERT INTO `subject` VALUES ('Allies.');
INSERT INTO `subject` VALUES ('Joy.');
INSERT INTO `subject` VALUES ('Suffering.');
INSERT INTO `subject` VALUES ('Dreams.');
INSERT INTO `subject` VALUES ('Tactics.');
INSERT INTO `subject` VALUES ('Investment.');
INSERT INTO `subject` VALUES ('Weapons.');
INSERT INTO `subject` VALUES ('Love.');
INSERT INTO `subject` VALUES ('Enemies.');
INSERT INTO `subject` VALUES ('A representative.');
INSERT INTO `subject` VALUES ('A plot.');
INSERT INTO `subject` VALUES ('Messages.');
INSERT INTO `subject` VALUES ('A plan.');
INSERT INTO `subject` VALUES ('Riches.');
INSERT INTO `subject` VALUES ('The public.');
INSERT INTO `subject` VALUES ('Competition.');
INSERT INTO `subject` VALUES ('Opposition.');
INSERT INTO `subject` VALUES ('Evil.');
INSERT INTO `subject` VALUES ('Liberty.');
INSERT INTO `subject` VALUES ('Rumour.');
INSERT INTO `subject` VALUES ('The innocent.');
INSERT INTO `subject` VALUES ('Adversities.');
INSERT INTO `subject` VALUES ('Hope.');
INSERT INTO `subject` VALUES ('Illusions.');
INSERT INTO `subject` VALUES ('Stalemate.');
INSERT INTO `subject` VALUES ('Art.');
INSERT INTO `subject` VALUES ('Failure.');
INSERT INTO `subject` VALUES ('News.');
INSERT INTO `subject` VALUES ('Pleasures.');
INSERT INTO `subject` VALUES ('Elements.');
INSERT INTO `subject` VALUES ('Nature.');
INSERT INTO `subject` VALUES ('Home.');
INSERT INTO `subject` VALUES ('Business.');
INSERT INTO `subject` VALUES ('The intellectual.');
INSERT INTO `subject` VALUES ('Information.');
INSERT INTO `subject` VALUES ('Ambush.');
INSERT INTO `subject` VALUES ('Power.');
INSERT INTO `subject` VALUES ('Plans.');
INSERT INTO `subject` VALUES ('Emotions.');
INSERT INTO `subject` VALUES ('Status quo.');
INSERT INTO `subject` VALUES ('Leadership.');
INSERT INTO `subject` VALUES ('Technology.');
INSERT INTO `subject` VALUES ('Military.');
INSERT INTO `subject` VALUES ('Illness.');
INSERT INTO `subject` VALUES ('Vehicle.');
INSERT INTO `subject` VALUES ('Victory.');
INSERT INTO `subject` VALUES ('Exterior factors.');
INSERT INTO `subject` VALUES ('A burden.');
INSERT INTO `subject` VALUES ('Energy.');
INSERT INTO `subject` VALUES ('Lies.');
INSERT INTO `subject` VALUES ('Magic.');
INSERT INTO `subject` VALUES ('Good.');
INSERT INTO `subject` VALUES ('Weather.');
INSERT INTO `subject` VALUES ('Portals.');
INSERT INTO `subject` VALUES ('Masses.');
INSERT INTO `subject` VALUES ('Realities.');
INSERT INTO `subject` VALUES ('The physical.');
INSERT INTO `subject` VALUES ('Death.');
INSERT INTO `subject` VALUES ('Goals.');
INSERT INTO `subject` VALUES ('Advice.');
INSERT INTO `subject` VALUES ('Travel.');



