CREATE TABLE "thing" (
                     `thing`	TEXT NOT NULL
                  );
INSERT INTO `thing` VALUES ('Above average arrows.');
INSERT INTO `thing` VALUES ('Scroll.');
INSERT INTO `thing` VALUES ('Damaged spyglass.');
INSERT INTO `thing` VALUES ('Boots.');
INSERT INTO `thing` VALUES ('Goblet.');
INSERT INTO `thing` VALUES ('Bottle.');
INSERT INTO `thing` VALUES ('Blacksmith tools.');
INSERT INTO `thing` VALUES ('Spear.');
INSERT INTO `thing` VALUES ('Below average bottle.');
INSERT INTO `thing` VALUES ('Old buckler.');
INSERT INTO `thing` VALUES ('Morningstar.');
INSERT INTO `thing` VALUES ('Wine.');
INSERT INTO `thing` VALUES ('Belt.');
INSERT INTO `thing` VALUES ('Whip.');
INSERT INTO `thing` VALUES ('Flail.');
INSERT INTO `thing` VALUES ('Herbs.');
INSERT INTO `thing` VALUES ('Necklace.');
INSERT INTO `thing` VALUES ('Key.');
INSERT INTO `thing` VALUES ('Quill and ink.');
INSERT INTO `thing` VALUES ('Staff.');
INSERT INTO `thing` VALUES ('Exquisite mace.');
INSERT INTO `thing` VALUES ('Broadsword.');
INSERT INTO `thing` VALUES ('Backpack.');
INSERT INTO `thing` VALUES ('Bracers.');
INSERT INTO `thing` VALUES ('High quality backpack.');
INSERT INTO `thing` VALUES ('War hammer.');
INSERT INTO `thing` VALUES ('Gold.');
INSERT INTO `thing` VALUES ('High quality spell book.');
INSERT INTO `thing` VALUES ('High quality pole arm.');
INSERT INTO `thing` VALUES ('High quality wand.');
INSERT INTO `thing` VALUES ('Old hood.');
INSERT INTO `thing` VALUES ('High quality coins.');
INSERT INTO `thing` VALUES ('Mead.');
INSERT INTO `thing` VALUES ('Jewelry.');
INSERT INTO `thing` VALUES ('Dress.');
INSERT INTO `thing` VALUES ('Crystal lens.');
INSERT INTO `thing` VALUES ('Tower shield.');
INSERT INTO `thing` VALUES ('Damaged ancient relic.');
INSERT INTO `thing` VALUES ('Lamp oil.');
INSERT INTO `thing` VALUES ('One of a kind oil lamp.');
INSERT INTO `thing` VALUES ('Below average shoes.');
INSERT INTO `thing` VALUES ('Very high quality belt.');
INSERT INTO `thing` VALUES ('Crossbow bolts.');
INSERT INTO `thing` VALUES ('Ancient artifact.');
INSERT INTO `thing` VALUES ('High quality artisan tools.');
INSERT INTO `thing` VALUES ('Chainmail armor.');
INSERT INTO `thing` VALUES ('High quality crystal lens.');
INSERT INTO `thing` VALUES ('Hunting bow.');
INSERT INTO `thing` VALUES ('Cheap rope.');
INSERT INTO `thing` VALUES ('Cheap ancient relic.');
INSERT INTO `thing` VALUES ('Cheap buckler.');
INSERT INTO `thing` VALUES ('Vial.');
INSERT INTO `thing` VALUES ('Lock picks.');
INSERT INTO `thing` VALUES ('Old shield.');
INSERT INTO `thing` VALUES ('Sling.');
INSERT INTO `thing` VALUES ('Claymore.');
INSERT INTO `thing` VALUES ('Pouch.');
INSERT INTO `thing` VALUES ('Shield.');
INSERT INTO `thing` VALUES ('Cheap poison.');
INSERT INTO `thing` VALUES ('Above average quill and ink.');
INSERT INTO `thing` VALUES ('Above average goblet.');
INSERT INTO `thing` VALUES ('High quality wine.');
INSERT INTO `thing` VALUES ('Elixir.');
INSERT INTO `thing` VALUES ('Rope.');
INSERT INTO `thing` VALUES ('Very high quality crossbow bolts.');
INSERT INTO `thing` VALUES ('Caltrops.');
INSERT INTO `thing` VALUES ('Gemstone.');
INSERT INTO `thing` VALUES ('Candle.');
INSERT INTO `thing` VALUES ('Above average flint and steel.');
INSERT INTO `thing` VALUES ('Below average wineskin.');
INSERT INTO `thing` VALUES ('Worn-out leather armor.');
INSERT INTO `thing` VALUES ('Exquisite figurine.');
INSERT INTO `thing` VALUES ('Urn.');
INSERT INTO `thing` VALUES ('Silver.');
INSERT INTO `thing` VALUES ('Artisan tools.');
INSERT INTO `thing` VALUES ('Helm.');
INSERT INTO `thing` VALUES ('Water clock.');
INSERT INTO `thing` VALUES ('Deteriorating crown.');
INSERT INTO `thing` VALUES ('Worn-out spell book.');
INSERT INTO `thing` VALUES ('Spell book.');
INSERT INTO `thing` VALUES ('Above average grappling hook.');
INSERT INTO `thing` VALUES ('Above average scimitar.');
INSERT INTO `thing` VALUES ('Coins.');
INSERT INTO `thing` VALUES ('Very high quality wine.');
INSERT INTO `thing` VALUES ('Excellent lamp oil.');
INSERT INTO `thing` VALUES ('Trail rations.');
INSERT INTO `thing` VALUES ('Flint and steel.');
INSERT INTO `thing` VALUES ('Lantern.');
INSERT INTO `thing` VALUES ('Very high quality precious stones.');
INSERT INTO `thing` VALUES ('Worn-out grappling hook.');
INSERT INTO `thing` VALUES ('Musical instrument.');
INSERT INTO `thing` VALUES ('Worn-out urn.');
INSERT INTO `thing` VALUES ('Worn-out gloves.');
INSERT INTO `thing` VALUES ('Superb poison.');
INSERT INTO `thing` VALUES ('Circlet.');
INSERT INTO `thing` VALUES ('Cheap quill and ink.');
INSERT INTO `thing` VALUES ('Oil lamp.');
INSERT INTO `thing` VALUES ('Below average hunting bow.');
INSERT INTO `thing` VALUES ('Worn-out ancient artifact.');
INSERT INTO `thing` VALUES ('Food.');
INSERT INTO `thing` VALUES ('Damaged leather armor.');
INSERT INTO `thing` VALUES ('Throwing axe.');
INSERT INTO `thing` VALUES ('Poison.');
INSERT INTO `thing` VALUES ('Below average elixir.');
INSERT INTO `thing` VALUES ('Deteriorating crossbow.');
INSERT INTO `thing` VALUES ('Broken dress.');
INSERT INTO `thing` VALUES ('Excellent precious stones.');
INSERT INTO `thing` VALUES ('Ancient relic.');
INSERT INTO `thing` VALUES ('Old spyglass.');
INSERT INTO `thing` VALUES ('Pole arm.');
INSERT INTO `thing` VALUES ('Clothing.');
INSERT INTO `thing` VALUES ('Old scroll.');
INSERT INTO `thing` VALUES ('Cheap pick axe.');
INSERT INTO `thing` VALUES ('High quality ring.');
INSERT INTO `thing` VALUES ('Scroll case.');
INSERT INTO `thing` VALUES ('Spyglass.');
INSERT INTO `thing` VALUES ('Damaged puzzle box.');
INSERT INTO `thing` VALUES ('Cheap urn.');
INSERT INTO `thing` VALUES ('Shoes.');
INSERT INTO `thing` VALUES ('Superb ancient tomb.');
INSERT INTO `thing` VALUES ('Old figurine.');
INSERT INTO `thing` VALUES ('Superb lantern.');
INSERT INTO `thing` VALUES ('Gloves.');
INSERT INTO `thing` VALUES ('Hat.');
INSERT INTO `thing` VALUES ('Mace.');
INSERT INTO `thing` VALUES ('Superb backpack.');
INSERT INTO `thing` VALUES ('High quality precious stones.');
INSERT INTO `thing` VALUES ('Wand.');
INSERT INTO `thing` VALUES ('One of a kind letters.');
INSERT INTO `thing` VALUES ('Above average coins.');
INSERT INTO `thing` VALUES ('Above average ring.');
INSERT INTO `thing` VALUES ('Broken crossbow bolts.');
INSERT INTO `thing` VALUES ('Crossbow.');
INSERT INTO `thing` VALUES ('Above average puzzle box.');
INSERT INTO `thing` VALUES ('Mug.');
INSERT INTO `thing` VALUES ('Battle axe.');
INSERT INTO `thing` VALUES ('Scimitar.');
INSERT INTO `thing` VALUES ('Potion.');
INSERT INTO `thing` VALUES ('Club.');
INSERT INTO `thing` VALUES ('Old crystal lens.');
INSERT INTO `thing` VALUES ('Book.');
INSERT INTO `thing` VALUES ('One of a kind arrows.');
INSERT INTO `thing` VALUES ('Below average clothing.');
INSERT INTO `thing` VALUES ('Damaged bracers.');
INSERT INTO `thing` VALUES ('Cheap scroll.');
INSERT INTO `thing` VALUES ('Below average dagger.');
INSERT INTO `thing` VALUES ('Old coins.');
INSERT INTO `thing` VALUES ('Puzzle box.');
INSERT INTO `thing` VALUES ('Cheap ring.');
INSERT INTO `thing` VALUES ('High quality mirror.');
INSERT INTO `thing` VALUES ('Very high quality goblet.');
INSERT INTO `thing` VALUES ('Longbow.');
INSERT INTO `thing` VALUES ('Exquisite hunting bow.');
INSERT INTO `thing` VALUES ('Above average mirror.');
INSERT INTO `thing` VALUES ('Mask.');
INSERT INTO `thing` VALUES ('Very high quality scimitar.');
INSERT INTO `thing` VALUES ('Crown.');
INSERT INTO `thing` VALUES ('High quality goblet.');
INSERT INTO `thing` VALUES ('Torch.');
INSERT INTO `thing` VALUES ('Excellent water clock.');
INSERT INTO `thing` VALUES ('Map.');
INSERT INTO `thing` VALUES ('Buckler.');
INSERT INTO `thing` VALUES ('High quality rope.');
INSERT INTO `thing` VALUES ('Leather armor.');
INSERT INTO `thing` VALUES ('High quality dress.');
INSERT INTO `thing` VALUES ('Above average gold.');
INSERT INTO `thing` VALUES ('Mirror.');
INSERT INTO `thing` VALUES ('Below average cloak.');
INSERT INTO `thing` VALUES ('High quality hunting bow.');
INSERT INTO `thing` VALUES ('High quality elixir.');
INSERT INTO `thing` VALUES ('Cheap trail rations.');
INSERT INTO `thing` VALUES ('Ring.');
INSERT INTO `thing` VALUES ('Below average circlet.');
INSERT INTO `thing` VALUES ('Old bag.');
INSERT INTO `thing` VALUES ('Ale.');
INSERT INTO `thing` VALUES ('Deteriorating necklace.');
INSERT INTO `thing` VALUES ('Superb gloves.');
INSERT INTO `thing` VALUES ('Paper.');
INSERT INTO `thing` VALUES ('Ancient tomb.');
INSERT INTO `thing` VALUES ('Very high quality food.');
INSERT INTO `thing` VALUES ('Dagger.');
INSERT INTO `thing` VALUES ('High quality gemstone.');
INSERT INTO `thing` VALUES ('High quality poison.');
INSERT INTO `thing` VALUES ('Below average shield.');
INSERT INTO `thing` VALUES ('Arrows.');
INSERT INTO `thing` VALUES ('High quality battle axe.');
INSERT INTO `thing` VALUES ('Below average pick axe.');
INSERT INTO `thing` VALUES ('Old precious stones.');
INSERT INTO `thing` VALUES ('Worn-out crystal lens.');
INSERT INTO `thing` VALUES ('Dragonscale armor.');
INSERT INTO `thing` VALUES ('Above average mask.');
INSERT INTO `thing` VALUES ('Superb pouch.');
INSERT INTO `thing` VALUES ('Old cloak.');
INSERT INTO `thing` VALUES ('Cheap spyglass.');
INSERT INTO `thing` VALUES ('High quality sling.');
INSERT INTO `thing` VALUES ('Broken figurine.');
INSERT INTO `thing` VALUES ('Old book.');
INSERT INTO `thing` VALUES ('Cloak.');
INSERT INTO `thing` VALUES ('Grappling hook.');
INSERT INTO `thing` VALUES ('Excellent spell book.');
INSERT INTO `thing` VALUES ('High quality lantern.');
INSERT INTO `thing` VALUES ('Superb helm.');
INSERT INTO `thing` VALUES ('Above average artisan tools.');
INSERT INTO `thing` VALUES ('Cheap spear.');
INSERT INTO `thing` VALUES ('Old dress.');
INSERT INTO `thing` VALUES ('Below average candle.');
INSERT INTO `thing` VALUES ('Hood.');
INSERT INTO `thing` VALUES ('Below average poison.');
INSERT INTO `thing` VALUES ('Old ale.');
INSERT INTO `thing` VALUES ('Above average buckler.');
INSERT INTO `thing` VALUES ('Old scroll case.');
INSERT INTO `thing` VALUES ('Cheap candle.');
INSERT INTO `thing` VALUES ('Long sword.');
INSERT INTO `thing` VALUES ('Cheap broadsword.');
INSERT INTO `thing` VALUES ('Worn-out mead.');
INSERT INTO `thing` VALUES ('Excellent vial.');
INSERT INTO `thing` VALUES ('Old boots.');
INSERT INTO `thing` VALUES ('Cheap water clock.');
INSERT INTO `thing` VALUES ('Deteriorating puzzle box.');
INSERT INTO `thing` VALUES ('Broken wineskin.');
INSERT INTO `thing` VALUES ('Damaged coins.');
INSERT INTO `thing` VALUES ('Worn-out hat.');
INSERT INTO `thing` VALUES ('High quality spear.');
INSERT INTO `thing` VALUES ('Cheap vial.');
INSERT INTO `thing` VALUES ('Worn-out wine.');
INSERT INTO `thing` VALUES ('High quality food.');
INSERT INTO `thing` VALUES ('Below average war hammer.');
INSERT INTO `thing` VALUES ('High quality puzzle box.');
INSERT INTO `thing` VALUES ('Above average spyglass.');
INSERT INTO `thing` VALUES ('Superb gemstone.');
INSERT INTO `thing` VALUES ('Figurine.');
INSERT INTO `thing` VALUES ('Worn-out clothing.');
INSERT INTO `thing` VALUES ('Below average necklace.');
INSERT INTO `thing` VALUES ('Above average poison.');
INSERT INTO `thing` VALUES ('Wineskin.');
INSERT INTO `thing` VALUES ('Worn-out bag.');
INSERT INTO `thing` VALUES ('Old hat.');
INSERT INTO `thing` VALUES ('Very high quality mace.');
INSERT INTO `thing` VALUES ('Below average spyglass.');
INSERT INTO `thing` VALUES ('Very high quality lock picks.');
INSERT INTO `thing` VALUES ('Below average wine.');
INSERT INTO `thing` VALUES ('Below average backpack.');
INSERT INTO `thing` VALUES ('Cheap scroll case.');
INSERT INTO `thing` VALUES ('Excellent torch.');
INSERT INTO `thing` VALUES ('Cheap dragonscale armor.');
INSERT INTO `thing` VALUES ('Precious stones.');
INSERT INTO `thing` VALUES ('High quality gold.');
INSERT INTO `thing` VALUES ('Excellent bag.');
INSERT INTO `thing` VALUES ('Very high quality claymore.');
INSERT INTO `thing` VALUES ('Below average figurine.');
INSERT INTO `thing` VALUES ('Short sword.');
INSERT INTO `thing` VALUES ('Pick axe.');
INSERT INTO `thing` VALUES ('Bag.');
INSERT INTO `thing` VALUES ('Below average broadsword.');
INSERT INTO `thing` VALUES ('Old candle.');
INSERT INTO `thing` VALUES ('Deteriorating coins.');
INSERT INTO `thing` VALUES ('Letters.');
INSERT INTO `thing` VALUES ('Superb vial.');
INSERT INTO `thing` VALUES ('Very high quality morningstar.');
INSERT INTO `thing` VALUES ('Above average mead.');
INSERT INTO `thing` VALUES ('Worn-out hood.');
INSERT INTO `thing` VALUES ('High quality candle.');
INSERT INTO `thing` VALUES ('Above average bottle.');
INSERT INTO `thing` VALUES ('Cheap mug.');
INSERT INTO `thing` VALUES ('Exquisite wine.');
INSERT INTO `thing` VALUES ('Below average sling.');
INSERT INTO `thing` VALUES ('Damaged hat.');
INSERT INTO `thing` VALUES ('Superb jewelry.');
INSERT INTO `thing` VALUES ('Below average artisan tools.');
INSERT INTO `thing` VALUES ('High quality musical instrument.');
INSERT INTO `thing` VALUES ('Above average gloves.');
INSERT INTO `thing` VALUES ('Excellent claymore.');
INSERT INTO `thing` VALUES ('Very high quality spell book.');
INSERT INTO `thing` VALUES ('Old flail.');
INSERT INTO `thing` VALUES ('Below average map.');
INSERT INTO `thing` VALUES ('Superb arrows.');
INSERT INTO `thing` VALUES ('Cheap arrows.');
INSERT INTO `thing` VALUES ('High quality bracers.');
INSERT INTO `thing` VALUES ('Old musical instrument.');
INSERT INTO `thing` VALUES ('Above average urn.');
INSERT INTO `thing` VALUES ('Below average ancient artifact.');
INSERT INTO `thing` VALUES ('Broken gold.');
INSERT INTO `thing` VALUES ('Deteriorating longbow.');
INSERT INTO `thing` VALUES ('Above average key.');
INSERT INTO `thing` VALUES ('Worn-out map.');
INSERT INTO `thing` VALUES ('Very high quality long sword.');
INSERT INTO `thing` VALUES ('Below average short sword.');
INSERT INTO `thing` VALUES ('Superb belt.');
INSERT INTO `thing` VALUES ('Cheap gold.');
INSERT INTO `thing` VALUES ('Above average herbs.');
INSERT INTO `thing` VALUES ('High quality mead.');
INSERT INTO `thing` VALUES ('High quality ancient tomb.');
INSERT INTO `thing` VALUES ('Excellent wine.');
INSERT INTO `thing` VALUES ('Damaged flint and steel.');
INSERT INTO `thing` VALUES ('High quality whip.');
INSERT INTO `thing` VALUES ('Superb spear.');
INSERT INTO `thing` VALUES ('Old quill and ink.');
INSERT INTO `thing` VALUES ('Superb short sword.');
INSERT INTO `thing` VALUES ('Deteriorating claymore.');
INSERT INTO `thing` VALUES ('Above average pole arm.');
INSERT INTO `thing` VALUES ('Worn-out shoes.');
INSERT INTO `thing` VALUES ('Cheap spell book.');
INSERT INTO `thing` VALUES ('Below average mask.');
INSERT INTO `thing` VALUES ('Very high quality ring.');
INSERT INTO `thing` VALUES ('One of a kind crossbow.');
INSERT INTO `thing` VALUES ('High quality throwing axe.');
INSERT INTO `thing` VALUES ('High quality hat.');
INSERT INTO `thing` VALUES ('Damaged wine.');
INSERT INTO `thing` VALUES ('High quality lock picks.');
INSERT INTO `thing` VALUES ('Damaged oil lamp.');
INSERT INTO `thing` VALUES ('Very high quality staff.');
INSERT INTO `thing` VALUES ('Deteriorating leather armor.');
INSERT INTO `thing` VALUES ('Cheap lantern.');
INSERT INTO `thing` VALUES ('One of a kind coins.');
INSERT INTO `thing` VALUES ('Above average hunting bow.');
INSERT INTO `thing` VALUES ('Below average ancient tomb.');
INSERT INTO `thing` VALUES ('One of a kind ancient tomb.');
INSERT INTO `thing` VALUES ('Cheap crossbow bolts.');
INSERT INTO `thing` VALUES ('Exquisite pole arm.');
INSERT INTO `thing` VALUES ('Very high quality blacksmith tools.');
INSERT INTO `thing` VALUES ('Cheap food.');
INSERT INTO `thing` VALUES ('Exquisite wineskin.');
INSERT INTO `thing` VALUES ('Cheap puzzle box.');
INSERT INTO `thing` VALUES ('Above average shield.');
INSERT INTO `thing` VALUES ('Superb precious stones.');
INSERT INTO `thing` VALUES ('Worn-out lantern.');
INSERT INTO `thing` VALUES ('Old pole arm.');
INSERT INTO `thing` VALUES ('Damaged rope.');
INSERT INTO `thing` VALUES ('Very high quality crystal lens.');
INSERT INTO `thing` VALUES ('High quality jewelry.');
INSERT INTO `thing` VALUES ('Excellent flail.');
INSERT INTO `thing` VALUES ('Below average gemstone.');
INSERT INTO `thing` VALUES ('Below average musical instrument.');
INSERT INTO `thing` VALUES ('Worn-out potion.');
INSERT INTO `thing` VALUES ('Worn-out buckler.');
INSERT INTO `thing` VALUES ('Worn-out bottle.');
INSERT INTO `thing` VALUES ('Below average crystal lens.');
INSERT INTO `thing` VALUES ('Excellent throwing axe.');
INSERT INTO `thing` VALUES ('Worn-out morningstar.');
INSERT INTO `thing` VALUES ('Very high quality cloak.');
INSERT INTO `thing` VALUES ('High quality war hammer.');
INSERT INTO `thing` VALUES ('High quality necklace.');
INSERT INTO `thing` VALUES ('High quality morningstar.');
INSERT INTO `thing` VALUES ('Superb potion.');
INSERT INTO `thing` VALUES ('High quality club.');
INSERT INTO `thing` VALUES ('Superb staff.');
INSERT INTO `thing` VALUES ('One of a kind gloves.');
INSERT INTO `thing` VALUES ('Superb food.');
INSERT INTO `thing` VALUES ('One of a kind gold.');
INSERT INTO `thing` VALUES ('Exquisite claymore.');
INSERT INTO `thing` VALUES ('Worn-out flail.');
INSERT INTO `thing` VALUES ('Worn-out dagger.');
INSERT INTO `thing` VALUES ('Excellent pick axe.');
INSERT INTO `thing` VALUES ('Above average wand.');
INSERT INTO `thing` VALUES ('Cheap mirror.');
INSERT INTO `thing` VALUES ('High quality mug.');
INSERT INTO `thing` VALUES ('Below average scroll.');
INSERT INTO `thing` VALUES ('Cheap hat.');
INSERT INTO `thing` VALUES ('Superb mirror.');
INSERT INTO `thing` VALUES ('Deteriorating dress.');



